// Code generated by entc, DO NOT EDIT.

package shopping

import (
	"time"

	"github.com/Frosin/shoplist-api-client-go/ent/schema"
)

const (
	// Label holds the string label denoting the shopping type in the database.
	Label = "shopping"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDate holds the string denoting the date vertex property in the database.
	FieldDate = "date"
	// FieldSum holds the string denoting the sum vertex property in the database.
	FieldSum = "sum"
	// FieldComplete holds the string denoting the complete vertex property in the database.
	FieldComplete = "complete"

	// Table holds the table name of the shopping in the database.
	Table = "shoppings"
	// ItemTable is the table the holds the item relation/edge.
	ItemTable = "items"
	// ItemInverseTable is the table name for the Item entity.
	// It exists in this package in order to avoid circular dependency with the "item" package.
	ItemInverseTable = "items"
	// ItemColumn is the table column denoting the item relation/edge.
	ItemColumn = "shopping_id"
	// ShopTable is the table the holds the shop relation/edge.
	ShopTable = "shoppings"
	// ShopInverseTable is the table name for the Shop entity.
	// It exists in this package in order to avoid circular dependency with the "shop" package.
	ShopInverseTable = "shops"
	// ShopColumn is the table column denoting the shop relation/edge.
	ShopColumn = "shop_id"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "shoppings"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for shopping fields.
var Columns = []string{
	FieldID,
	FieldDate,
	FieldSum,
	FieldComplete,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Shopping type.
var ForeignKeys = []string{
	"shop_id",
	"user_id",
}

var (
	fields = schema.Shopping{}.Fields()

	// descDate is the schema descriptor for date field.
	descDate = fields[0].Descriptor()
	// DefaultDate holds the default value on creation for the date field.
	DefaultDate = descDate.Default.(func() time.Time)

	// descSum is the schema descriptor for sum field.
	descSum = fields[1].Descriptor()
	// DefaultSum holds the default value on creation for the sum field.
	DefaultSum = descSum.Default.(int)

	// descComplete is the schema descriptor for complete field.
	descComplete = fields[2].Descriptor()
	// DefaultComplete holds the default value on creation for the complete field.
	DefaultComplete = descComplete.Default.(bool)
)
