// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getComingShoppingsStmt, err = db.PrepareContext(ctx, getComingShoppings); err != nil {
		return nil, fmt.Errorf("error preparing query GetComingShoppings: %w", err)
	}
	if q.getGoodsByShoppingIDStmt, err = db.PrepareContext(ctx, getGoodsByShoppingID); err != nil {
		return nil, fmt.Errorf("error preparing query GetGoodsByShoppingID: %w", err)
	}
	if q.getLastShoppingStmt, err = db.PrepareContext(ctx, getLastShopping); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastShopping: %w", err)
	}
	if q.getShoppingByNameStmt, err = db.PrepareContext(ctx, getShoppingByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetShoppingByName: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getComingShoppingsStmt != nil {
		if cerr := q.getComingShoppingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getComingShoppingsStmt: %w", cerr)
		}
	}
	if q.getGoodsByShoppingIDStmt != nil {
		if cerr := q.getGoodsByShoppingIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGoodsByShoppingIDStmt: %w", cerr)
		}
	}
	if q.getLastShoppingStmt != nil {
		if cerr := q.getLastShoppingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastShoppingStmt: %w", cerr)
		}
	}
	if q.getShoppingByNameStmt != nil {
		if cerr := q.getShoppingByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getShoppingByNameStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                       DBTX
	tx                       *sql.Tx
	getComingShoppingsStmt   *sql.Stmt
	getGoodsByShoppingIDStmt *sql.Stmt
	getLastShoppingStmt      *sql.Stmt
	getShoppingByNameStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                       tx,
		tx:                       tx,
		getComingShoppingsStmt:   q.getComingShoppingsStmt,
		getGoodsByShoppingIDStmt: q.getGoodsByShoppingIDStmt,
		getLastShoppingStmt:      q.getLastShoppingStmt,
		getShoppingByNameStmt:    q.getShoppingByNameStmt,
	}
}
