// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
)

type Shop struct {
	ID   int32          `json:"id"`
	Name sql.NullString `json:"name"`
}

type ShopList struct {
	ID          int32          `json:"id"`
	ProductName sql.NullString `json:"product_name"`
	Quantity    sql.NullInt32  `json:"quantity"`
	CategoryID  sql.NullInt32  `json:"category_id"`
	Complete    sql.NullInt32  `json:"complete"`
	ListID      sql.NullInt32  `json:"list_id"`
}

type Shopping struct {
	ID       int32          `json:"id"`
	Date     sql.NullString `json:"date"`
	Sum      sql.NullInt32  `json:"sum"`
	ShopID   sql.NullInt32  `json:"shop_id"`
	Complete sql.NullInt32  `json:"complete"`
	Time     sql.NullString `json:"time"`
	OwnerID  sql.NullInt32  `json:"owner_id"`
}

type User struct {
	ID               int32          `json:"id"`
	TelegramID       int32          `json:"telegram_id"`
	TelegramUsername sql.NullString `json:"telegram_username"`
	ComunityID       string         `json:"comunity_id"`
	Token            sql.NullString `json:"token"`
	ChatID           sql.NullInt32  `json:"chat_id"`
}
