// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package shoplist

import (
	"context"
	"database/sql"
)

const getGoodsByShoppingID = `-- name: GetGoodsByShoppingID :many
SELECT id, product_name, quantity, category_id, complete, list_id FROM shop_list
WHERE list_id = $1
`

func (q *Queries) GetGoodsByShoppingID(ctx context.Context, listID sql.NullInt32) ([]ShopList, error) {
	rows, err := q.query(ctx, q.getGoodsByShoppingIDStmt, getGoodsByShoppingID, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopList
	for rows.Next() {
		var i ShopList
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.Quantity,
			&i.CategoryID,
			&i.Complete,
			&i.ListID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
