// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/Frosin/shoplist-api-client-go/ent/item"
	"github.com/Frosin/shoplist-api-client-go/ent/shopping"

	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "product_name", Type: field.TypeString},
		{Name: "quantity", Type: field.TypeInt, Default: item.DefaultQuantity},
		{Name: "category_id", Type: field.TypeInt, Default: item.DefaultCategoryID},
		{Name: "complete", Type: field.TypeBool, Default: item.DefaultComplete},
		{Name: "shopping_item", Type: field.TypeInt, Nullable: true},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "items_shoppings_item",
				Columns: []*schema.Column{ItemsColumns[5]},

				RefColumns: []*schema.Column{ShoppingsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ShopsColumns holds the columns for the "shops" table.
	ShopsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// ShopsTable holds the schema information for the "shops" table.
	ShopsTable = &schema.Table{
		Name:        "shops",
		Columns:     ShopsColumns,
		PrimaryKey:  []*schema.Column{ShopsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ShoppingsColumns holds the columns for the "shoppings" table.
	ShoppingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "date", Type: field.TypeTime},
		{Name: "sum", Type: field.TypeInt, Default: shopping.DefaultSum},
		{Name: "complete", Type: field.TypeBool, Default: shopping.DefaultComplete},
		{Name: "shop_shopping", Type: field.TypeInt, Nullable: true},
		{Name: "user_shopping", Type: field.TypeInt, Nullable: true},
	}
	// ShoppingsTable holds the schema information for the "shoppings" table.
	ShoppingsTable = &schema.Table{
		Name:       "shoppings",
		Columns:    ShoppingsColumns,
		PrimaryKey: []*schema.Column{ShoppingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "shoppings_shops_shopping",
				Columns: []*schema.Column{ShoppingsColumns[4]},

				RefColumns: []*schema.Column{ShopsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "shoppings_users_shopping",
				Columns: []*schema.Column{ShoppingsColumns[5]},

				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "telegram_id", Type: field.TypeInt64},
		{Name: "telegram_username", Type: field.TypeString},
		{Name: "comunity_id", Type: field.TypeString},
		{Name: "token", Type: field.TypeString},
		{Name: "chat_id", Type: field.TypeInt64},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
		Indexes: []*schema.Index{
			{
				Name:    "user_telegram_id_comunity_id_token",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1], UsersColumns[3], UsersColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ItemsTable,
		ShopsTable,
		ShoppingsTable,
		UsersTable,
	}
)

func init() {
	ItemsTable.ForeignKeys[0].RefTable = ShoppingsTable
	ShoppingsTable.ForeignKeys[0].RefTable = ShopsTable
	ShoppingsTable.ForeignKeys[1].RefTable = UsersTable
}
