// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/Frosin/shoplist-api-client-go/ent/item"
	"github.com/Frosin/shoplist-api-client-go/ent/predicate"
	"github.com/Frosin/shoplist-api-client-go/ent/shop"
	"github.com/Frosin/shoplist-api-client-go/ent/shopping"
	"github.com/Frosin/shoplist-api-client-go/ent/user"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ShoppingUpdate is the builder for updating Shopping entities.
type ShoppingUpdate struct {
	config
	hooks      []Hook
	mutation   *ShoppingMutation
	predicates []predicate.Shopping
}

// Where adds a new predicate for the builder.
func (su *ShoppingUpdate) Where(ps ...predicate.Shopping) *ShoppingUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetDate sets the date field.
func (su *ShoppingUpdate) SetDate(t time.Time) *ShoppingUpdate {
	su.mutation.SetDate(t)
	return su
}

// SetNillableDate sets the date field if the given value is not nil.
func (su *ShoppingUpdate) SetNillableDate(t *time.Time) *ShoppingUpdate {
	if t != nil {
		su.SetDate(*t)
	}
	return su
}

// SetSum sets the sum field.
func (su *ShoppingUpdate) SetSum(i int) *ShoppingUpdate {
	su.mutation.ResetSum()
	su.mutation.SetSum(i)
	return su
}

// SetNillableSum sets the sum field if the given value is not nil.
func (su *ShoppingUpdate) SetNillableSum(i *int) *ShoppingUpdate {
	if i != nil {
		su.SetSum(*i)
	}
	return su
}

// AddSum adds i to sum.
func (su *ShoppingUpdate) AddSum(i int) *ShoppingUpdate {
	su.mutation.AddSum(i)
	return su
}

// SetComplete sets the complete field.
func (su *ShoppingUpdate) SetComplete(b bool) *ShoppingUpdate {
	su.mutation.SetComplete(b)
	return su
}

// SetNillableComplete sets the complete field if the given value is not nil.
func (su *ShoppingUpdate) SetNillableComplete(b *bool) *ShoppingUpdate {
	if b != nil {
		su.SetComplete(*b)
	}
	return su
}

// AddItemIDs adds the item edge to Item by ids.
func (su *ShoppingUpdate) AddItemIDs(ids ...int) *ShoppingUpdate {
	su.mutation.AddItemIDs(ids...)
	return su
}

// AddItem adds the item edges to Item.
func (su *ShoppingUpdate) AddItem(i ...*Item) *ShoppingUpdate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return su.AddItemIDs(ids...)
}

// SetShopID sets the shop edge to Shop by id.
func (su *ShoppingUpdate) SetShopID(id int) *ShoppingUpdate {
	su.mutation.SetShopID(id)
	return su
}

// SetNillableShopID sets the shop edge to Shop by id if the given value is not nil.
func (su *ShoppingUpdate) SetNillableShopID(id *int) *ShoppingUpdate {
	if id != nil {
		su = su.SetShopID(*id)
	}
	return su
}

// SetShop sets the shop edge to Shop.
func (su *ShoppingUpdate) SetShop(s *Shop) *ShoppingUpdate {
	return su.SetShopID(s.ID)
}

// SetUserID sets the user edge to User by id.
func (su *ShoppingUpdate) SetUserID(id int) *ShoppingUpdate {
	su.mutation.SetUserID(id)
	return su
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (su *ShoppingUpdate) SetNillableUserID(id *int) *ShoppingUpdate {
	if id != nil {
		su = su.SetUserID(*id)
	}
	return su
}

// SetUser sets the user edge to User.
func (su *ShoppingUpdate) SetUser(u *User) *ShoppingUpdate {
	return su.SetUserID(u.ID)
}

// RemoveItemIDs removes the item edge to Item by ids.
func (su *ShoppingUpdate) RemoveItemIDs(ids ...int) *ShoppingUpdate {
	su.mutation.RemoveItemIDs(ids...)
	return su
}

// RemoveItem removes item edges to Item.
func (su *ShoppingUpdate) RemoveItem(i ...*Item) *ShoppingUpdate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return su.RemoveItemIDs(ids...)
}

// ClearShop clears the shop edge to Shop.
func (su *ShoppingUpdate) ClearShop() *ShoppingUpdate {
	su.mutation.ClearShop()
	return su
}

// ClearUser clears the user edge to User.
func (su *ShoppingUpdate) ClearUser() *ShoppingUpdate {
	su.mutation.ClearUser()
	return su
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *ShoppingUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ShoppingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *ShoppingUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ShoppingUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ShoppingUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *ShoppingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   shopping.Table,
			Columns: shopping.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: shopping.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Date(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shopping.FieldDate,
		})
	}
	if value, ok := su.mutation.Sum(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: shopping.FieldSum,
		})
	}
	if value, ok := su.mutation.AddedSum(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: shopping.FieldSum,
		})
	}
	if value, ok := su.mutation.Complete(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: shopping.FieldComplete,
		})
	}
	if nodes := su.mutation.RemovedItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ItemTable,
			Columns: []string{shopping.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: item.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ItemTable,
			Columns: []string{shopping.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: item.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopping.ShopTable,
			Columns: []string{shopping.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shop.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopping.ShopTable,
			Columns: []string{shopping.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shop.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopping.UserTable,
			Columns: []string{shopping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopping.UserTable,
			Columns: []string{shopping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shopping.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ShoppingUpdateOne is the builder for updating a single Shopping entity.
type ShoppingUpdateOne struct {
	config
	hooks    []Hook
	mutation *ShoppingMutation
}

// SetDate sets the date field.
func (suo *ShoppingUpdateOne) SetDate(t time.Time) *ShoppingUpdateOne {
	suo.mutation.SetDate(t)
	return suo
}

// SetNillableDate sets the date field if the given value is not nil.
func (suo *ShoppingUpdateOne) SetNillableDate(t *time.Time) *ShoppingUpdateOne {
	if t != nil {
		suo.SetDate(*t)
	}
	return suo
}

// SetSum sets the sum field.
func (suo *ShoppingUpdateOne) SetSum(i int) *ShoppingUpdateOne {
	suo.mutation.ResetSum()
	suo.mutation.SetSum(i)
	return suo
}

// SetNillableSum sets the sum field if the given value is not nil.
func (suo *ShoppingUpdateOne) SetNillableSum(i *int) *ShoppingUpdateOne {
	if i != nil {
		suo.SetSum(*i)
	}
	return suo
}

// AddSum adds i to sum.
func (suo *ShoppingUpdateOne) AddSum(i int) *ShoppingUpdateOne {
	suo.mutation.AddSum(i)
	return suo
}

// SetComplete sets the complete field.
func (suo *ShoppingUpdateOne) SetComplete(b bool) *ShoppingUpdateOne {
	suo.mutation.SetComplete(b)
	return suo
}

// SetNillableComplete sets the complete field if the given value is not nil.
func (suo *ShoppingUpdateOne) SetNillableComplete(b *bool) *ShoppingUpdateOne {
	if b != nil {
		suo.SetComplete(*b)
	}
	return suo
}

// AddItemIDs adds the item edge to Item by ids.
func (suo *ShoppingUpdateOne) AddItemIDs(ids ...int) *ShoppingUpdateOne {
	suo.mutation.AddItemIDs(ids...)
	return suo
}

// AddItem adds the item edges to Item.
func (suo *ShoppingUpdateOne) AddItem(i ...*Item) *ShoppingUpdateOne {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return suo.AddItemIDs(ids...)
}

// SetShopID sets the shop edge to Shop by id.
func (suo *ShoppingUpdateOne) SetShopID(id int) *ShoppingUpdateOne {
	suo.mutation.SetShopID(id)
	return suo
}

// SetNillableShopID sets the shop edge to Shop by id if the given value is not nil.
func (suo *ShoppingUpdateOne) SetNillableShopID(id *int) *ShoppingUpdateOne {
	if id != nil {
		suo = suo.SetShopID(*id)
	}
	return suo
}

// SetShop sets the shop edge to Shop.
func (suo *ShoppingUpdateOne) SetShop(s *Shop) *ShoppingUpdateOne {
	return suo.SetShopID(s.ID)
}

// SetUserID sets the user edge to User by id.
func (suo *ShoppingUpdateOne) SetUserID(id int) *ShoppingUpdateOne {
	suo.mutation.SetUserID(id)
	return suo
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (suo *ShoppingUpdateOne) SetNillableUserID(id *int) *ShoppingUpdateOne {
	if id != nil {
		suo = suo.SetUserID(*id)
	}
	return suo
}

// SetUser sets the user edge to User.
func (suo *ShoppingUpdateOne) SetUser(u *User) *ShoppingUpdateOne {
	return suo.SetUserID(u.ID)
}

// RemoveItemIDs removes the item edge to Item by ids.
func (suo *ShoppingUpdateOne) RemoveItemIDs(ids ...int) *ShoppingUpdateOne {
	suo.mutation.RemoveItemIDs(ids...)
	return suo
}

// RemoveItem removes item edges to Item.
func (suo *ShoppingUpdateOne) RemoveItem(i ...*Item) *ShoppingUpdateOne {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return suo.RemoveItemIDs(ids...)
}

// ClearShop clears the shop edge to Shop.
func (suo *ShoppingUpdateOne) ClearShop() *ShoppingUpdateOne {
	suo.mutation.ClearShop()
	return suo
}

// ClearUser clears the user edge to User.
func (suo *ShoppingUpdateOne) ClearUser() *ShoppingUpdateOne {
	suo.mutation.ClearUser()
	return suo
}

// Save executes the query and returns the updated entity.
func (suo *ShoppingUpdateOne) Save(ctx context.Context) (*Shopping, error) {

	var (
		err  error
		node *Shopping
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ShoppingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ShoppingUpdateOne) SaveX(ctx context.Context) *Shopping {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *ShoppingUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ShoppingUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *ShoppingUpdateOne) sqlSave(ctx context.Context) (s *Shopping, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   shopping.Table,
			Columns: shopping.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: shopping.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, fmt.Errorf("missing Shopping.ID for update")
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.Date(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shopping.FieldDate,
		})
	}
	if value, ok := suo.mutation.Sum(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: shopping.FieldSum,
		})
	}
	if value, ok := suo.mutation.AddedSum(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: shopping.FieldSum,
		})
	}
	if value, ok := suo.mutation.Complete(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: shopping.FieldComplete,
		})
	}
	if nodes := suo.mutation.RemovedItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ItemTable,
			Columns: []string{shopping.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: item.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopping.ItemTable,
			Columns: []string{shopping.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: item.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopping.ShopTable,
			Columns: []string{shopping.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shop.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopping.ShopTable,
			Columns: []string{shopping.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: shop.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopping.UserTable,
			Columns: []string{shopping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopping.UserTable,
			Columns: []string{shopping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Shopping{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shopping.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
