// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/Frosin/shoplist-api-client-go/ent/user"
	"github.com/facebookincubator/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TelegramID holds the value of the "telegram_id" field.
	TelegramID int64 `json:"telegram_id,omitempty"`
	// TelegramUsername holds the value of the "telegram_username" field.
	TelegramUsername string `json:"telegram_username,omitempty"`
	// ComunityID holds the value of the "comunity_id" field.
	ComunityID string `json:"comunity_id,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// ChatID holds the value of the "chat_id" field.
	ChatID int64 `json:"chat_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges UserEdges `json:"edges"`
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Shopping holds the value of the shopping edge.
	Shopping []*Shopping
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ShoppingOrErr returns the Shopping value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ShoppingOrErr() ([]*Shopping, error) {
	if e.loadedTypes[0] {
		return e.Shopping, nil
	}
	return nil, &NotLoadedError{edge: "shopping"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullInt64{},  // telegram_id
		&sql.NullString{}, // telegram_username
		&sql.NullString{}, // comunity_id
		&sql.NullString{}, // token
		&sql.NullInt64{},  // chat_id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(values ...interface{}) error {
	if m, n := len(values), len(user.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	u.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field telegram_id", values[0])
	} else if value.Valid {
		u.TelegramID = value.Int64
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field telegram_username", values[1])
	} else if value.Valid {
		u.TelegramUsername = value.String
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field comunity_id", values[2])
	} else if value.Valid {
		u.ComunityID = value.String
	}
	if value, ok := values[3].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field token", values[3])
	} else if value.Valid {
		u.Token = value.String
	}
	if value, ok := values[4].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field chat_id", values[4])
	} else if value.Valid {
		u.ChatID = value.Int64
	}
	return nil
}

// QueryShopping queries the shopping edge of the User.
func (u *User) QueryShopping() *ShoppingQuery {
	return (&UserClient{config: u.config}).QueryShopping(u)
}

// Update returns a builder for updating this User.
// Note that, you need to call User.Unwrap() before calling this method, if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return (&UserClient{config: u.config}).UpdateOne(u)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v", u.ID))
	builder.WriteString(", telegram_id=")
	builder.WriteString(fmt.Sprintf("%v", u.TelegramID))
	builder.WriteString(", telegram_username=")
	builder.WriteString(u.TelegramUsername)
	builder.WriteString(", comunity_id=")
	builder.WriteString(u.ComunityID)
	builder.WriteString(", token=")
	builder.WriteString(u.Token)
	builder.WriteString(", chat_id=")
	builder.WriteString(fmt.Sprintf("%v", u.ChatID))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User

func (u Users) config(cfg config) {
	for _i := range u {
		u[_i].config = cfg
	}
}
