openapi: '3.0.0'
info:
  title: Shoplist api service
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  "/getGoods/{shoppingID}":
    parameters:
    - $ref: "#/components/parameters/shoppingID"
    get:
      operationId: getGoods
      tags:
        - Shopping
      summary: Список покупок
      responses:
        "200":
          $ref: "#/components/responses/Goods_200"
        "404":
          $ref: "#/components/responses/Base_404"
        "405":
          $ref: "#/components/responses/Base_405"
        "500":
          $ref: "#/components/responses/Base_500"
  "/getComingShoppings/{date}":
    parameters:
    - $ref: "#/components/parameters/date"
  "/lastShopping":
  "/addItem":
  "/addShopping":  
components:
  schemas:
      Base:
        description: Возвращает статус ответа
        type: object
        properties:
          version:
            type: string
            description: Вкрсия ответа сервиса
            example: 1.0.0
      Success:
        description: Ответ успешно получен
        allOf:
          - $ref: "#/components/schemas/Base"
          - type: object
            title: Success
            properties:
              message:
                type: string
                description: Сообщение ответа
                example: Success
              errors:
                type: array
                items: {}
                description: Ошибки ответа
            required:
              - message
              - errors
      Error:
        description: Ошибка !!11
        allOf:
          - $ref: "#/components/schemas/Base"
          - type: object
            title: Error
            properties:
              data:
                example: null
            required:
              - data
      Error_404:
        allOf:
          - $ref: "#/components/schemas/Error"
          - type: object
            title: Error_404
            properties:
              message:
                type: string
                description: сообщение об ошибке
                example: Entity not found
              errors:
                type: array
                items: {}
                example: null
            required: 
              - message
              - errors
      Error_405:
        allOf:
          - $ref: "#/components/schemas/Error"
          - type: object
            title: Error_405
            properties:
              message:
                type: string
                description: сообщение ответа
                example: Method ${METHOD} not allowed
              errors:
                type: array
                items: {}
                example: null
      Error_500:
        allOf:
          - $ref: "#/components/schemas/Error"
          - type: object
            title: Error_500
            properties:
              message:
                type: string
                description: сообщение ответа
                example: Internal server error
              errors:
                example: null
            required:
              - message
              - errors
      Shopping_item_params:
        title: Параметры товара в покупке
        properties:
          ID:
            type: string
            description: Идентификатор товара
            example: 55
          ProductName:
            type: string
            description: Наименование товара
            example: Хлеб
            minLength: 1
          Quantity:
            type: integer
            description: Количество товара
            example: 1
          CategoryID:
            type: integer
            description: Идентификатор категории товара
            example: 5
          Complete:  
            type: boolean
            description: Флаг выполнения покупки
            example: true  
          ListID:
            type: integer
            description: Идентификатор списка покупок
            example: 5
      Shopping_item:
        allOf:
          - title: Товар в списке покупок
            type: object
          - $ref: "#/components/schemas/Shopping_item_params"  
        required:
          - ID
          - ProductName
          - Quantity
          - CategoryID
          - Complete
          - ListID
  responses:
      Base_404:
        description: Not found
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Error_404"
      Base_405:
        description: Invalid method
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Error_405"
      Base_500:
        description: Internal server error
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Error_500"
      Goods_200:
        description: Список товаров покупки
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Success"
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        $ref: "#/components/schemas/Shopping_item"
  parameters:
    shoppingID:
      name: shoppingID
      in: path
      required: true
      description: Идентификатор покупки
      schema:
        type: integer