// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Shop is the predicate function for shop builders.
type Shop func(*sql.Selector)

// Shopping is the predicate function for shopping builders.
type Shopping func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
